// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqJIC_wEjC_1bwl6vJ1NTbkmwUi7ETB8c',
    appId: '1:833574280637:web:78950add318a9381bac6d4',
    messagingSenderId: '833574280637',
    projectId: 'hunarmand-a5975',
    authDomain: 'hunarmand-a5975.firebaseapp.com',
    storageBucket: 'hunarmand-a5975.firebasestorage.app',
    measurementId: 'G-0T9EG3XN2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXYwX2OMQLbe4r6A4Pcb1aos1Ty_sXcxE',
    appId: '1:833574280637:android:03bbddefa7039ce0bac6d4',
    messagingSenderId: '833574280637',
    projectId: 'hunarmand-a5975',
    storageBucket: 'hunarmand-a5975.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5goDsvyIgSG6JOSnIjsJu47VhV2IV5H8',
    appId: '1:833574280637:ios:336a856f190c5c06bac6d4',
    messagingSenderId: '833574280637',
    projectId: 'hunarmand-a5975',
    storageBucket: 'hunarmand-a5975.firebasestorage.app',
    iosBundleId: 'com.example.hunarmand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5goDsvyIgSG6JOSnIjsJu47VhV2IV5H8',
    appId: '1:833574280637:ios:336a856f190c5c06bac6d4',
    messagingSenderId: '833574280637',
    projectId: 'hunarmand-a5975',
    storageBucket: 'hunarmand-a5975.firebasestorage.app',
    iosBundleId: 'com.example.hunarmand',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqJIC_wEjC_1bwl6vJ1NTbkmwUi7ETB8c',
    appId: '1:833574280637:web:6ff29b743c6aaa03bac6d4',
    messagingSenderId: '833574280637',
    projectId: 'hunarmand-a5975',
    authDomain: 'hunarmand-a5975.firebaseapp.com',
    storageBucket: 'hunarmand-a5975.firebasestorage.app',
    measurementId: 'G-1Z5RZE50F1',
  );
}
