name: SkillLink
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  intl: ^0.20.2
  google_sign_in: ^6.2.2
  fl_chart: ^0.70.2
  flutter_riverpod: ^2.6.1
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  provider: ^6.1.2
  image_picker: ^1.1.2
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.4
  push: ^3.3.3
  flutter_local_notifications: ^18.0.1
  table_calendar: ^3.2.0
  google_maps_flutter: ^2.12.2
  share_plus: ^10.1.4
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  permission_handler: ^12.0.0+1
  app_settings: ^6.1.1  
  package_info_plus: ^8.3.0
  get_it: ^8.0.3
  http: ^1.4.0
  uuid: ^4.5.1
  record: ^6.0.0
  path_provider: ^2.1.5
  audioplayers: ^6.4.0
  shimmer: ^3.0.0
  lottie: ^3.3.1
  crypto: ^3.0.6
  flutter_cache_manager: ^3.4.1
  firebase_app_check: ^0.3.2+6
  sqflite: ^2.4.1
  get: ^4.7.2
  local_auth: ^2.3.0
  firebase_analytics: ^11.4.6
  cloud_functions: ^5.5.1
  firebase_crashlytics: ^4.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/logo.png
    - assets/onboarding1.png
    - assets/onboarding2.png
    - assets/onboarding3.png
    
